modLoader="javafml" #mandatory

loaderVersion="[31,)"

issueTrackerURL="https://github.com/Novarch129/JoJo-s-Blocky-Adventure/issues"

[[mods]]

modId="jojomod"

version="1.15.2-1.0.0.1"

displayName="JoJo's Bizarre Survival"

updateJSONURL="http://example.com/"

displayURL="https://github.com/Novarch129/JoJo-s-Bizarre-Survival"

logoFile="logo.png"

credits="Novarch"

authors="Novarch"

description='''
	A mod that adds Stands from JoJo's Bizarre Adventure into Minecraft.
'''

[[dependencies.jojomod]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.jojomod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
